# Generated by Django 3.2.13 on 2022-05-13 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_logindetails_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='datetime',
        ),
        migrations.AddField(
            model_name='logindetails',
            name='logindatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
