# Generated by Django 3.2.13 on 2022-05-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_logindetails_logoutdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='logoutdatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
