# Generated by Django 3.2.13 on 2022-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='logindatetime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='logoutdatetime',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
    ]
