# Generated by Django 3.2.13 on 2022-05-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20220531_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='logindatetime',
        ),
        migrations.RemoveField(
            model_name='logindetails',
            name='logoutdatetime',
        ),
        migrations.AddField(
            model_name='logindetails',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='logtime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='outtime',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
    ]
