# Generated by Django 3.2.13 on 2022-07-03 11:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_logindetails_outtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cname', models.CharField(max_length=250)),
                ('starttime', models.DateField(blank=True)),
                ('endtime', models.DateField(blank=True)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TodayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField(auto_now_add=True)),
                ('workon', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.projectdetails')),
            ],
        ),
    ]
