# Generated by Django 3.2.13 on 2022-07-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_projectdetails_todayreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayreport',
            name='tdate',
            field=models.CharField(max_length=10),
        ),
    ]
