# Generated by Django 3.2.13 on 2022-06-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('ta', models.IntegerField()),
                ('sa', models.IntegerField()),
                ('total', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
