# Generated by Django 3.2.13 on 2022-06-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_salerydetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerydetails',
            old_name='total',
            new_name='totalsalary',
        ),
    ]
