# Generated by Django 3.2.13 on 2022-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_salerydetails_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
