# Generated by Django 3.2.13 on 2022-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_status',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin'), ('HR', 'HR')], default='1', max_length=20),
        ),
    ]
