# Generated by Django 3.2.13 on 2022-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_employee_emp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joiningdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
