# Generated by Django 3.2.13 on 2022-06-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_alter_employee_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_status',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin'), ('HR', 'HR')], default='Employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joiningdate',
            field=models.DateField(),
        ),
    ]
