# Generated by Django 3.2.13 on 2022-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_leavemanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
