# Generated by Django 3.2.13 on 2022-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_leavemanagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='fromdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='todate',
            field=models.DateField(blank=True),
        ),
    ]
