# Generated by Django 3.2.13 on 2022-06-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_auto_20220606_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='reason',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
