# Generated by Django 3.2.13 on 2022-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_alter_leavemanagement_rejectionreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='workeniversary',
            field=models.IntegerField(default=0),
        ),
    ]
