# Generated by Django 3.2.13 on 2022-06-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0044_employee_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='increment',
        ),
    ]
