# Generated by Django 3.2.13 on 2022-06-07 12:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0047_questions_quizschedule_userresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
