# Generated by Django 3.2.13 on 2022-06-08 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0048_alter_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
