# Generated by Django 3.2.13 on 2022-06-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0049_userresponse_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
