# Generated by Django 3.2.13 on 2022-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0053_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
